import type { PresetCollection, PresetPrompt, SmileyPreset } from "./types";
import { defaultPresetGenerationSettings } from "./generation";

export const dynamicPromptIds = {
    character: "charDescription",
    characterPersonality: "charPersonality",
    chatExamples: "dialogueExamples",
    scenario: "scenario",
    personaDescription: "personaDescription",
    worldInfoBefore: "worldInfoBefore",
    worldInfoAfter: "worldInfoAfter",
    chatHistory: "chatHistory",
} as const;

export function createDefaultPreset(now = new Date().toISOString()): SmileyPreset {
    const prompts: PresetPrompt[] = [
        {
            id: "69994633-aef6-4892-85d6-a47ddb7d03d6",
            title: "Assistant Instructions",
            role: "system",
            content: [
                "You are an experienced and passionate aesthetic Roleplay Game Master, specializing in crafting immersive and engaging narratives for players.",
                "Your expertise lies in creating rich, detailed worlds and characters that captivate the imagination.",
                "You excel at adapting to player choices, weaving intricate storylines, and fostering a collaborative storytelling environment.",
                "Your goal is to provide an unforgettable roleplaying experience that sparks creativity and deepens player engagement.",
            ].join("\n"),
            systemPrompt: true,
            marker: false,
            injectionPosition: "none",
            injectionDepth: 0,
            forbidOverrides: false,
        },
        {
            id: dynamicPromptIds.character,
            title: "Character Description",
            role: "system",
            content: [
                "<{{char}}_description>",
                "{{char_description}}",
                "</{{char}}_description>",
                "",
                "<{{char}}_system_prompt>",
                "{{char_system_prompt}}",
                "</{{char}}_system_prompt>",
            ].join("\n"),
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "after-character",
        },
        {
            id: dynamicPromptIds.characterPersonality,
            title: "Character Personality",
            role: "system",
            content: "",
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "after-character",
        },
        {
            id: dynamicPromptIds.personaDescription,
            title: "Persona Description",
            role: "system",
            content: "",
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "after-character",
        },
        {
            id: dynamicPromptIds.worldInfoBefore,
            title: "World Info Before",
            role: "system",
            content: "",
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "before-character",
        },
        {
            id: dynamicPromptIds.worldInfoAfter,
            title: "World Info After",
            role: "system",
            content: "",
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "after-character",
        },
        {
            id: dynamicPromptIds.scenario,
            title: "Scenario",
            role: "system",
            content: [
                "<scenario>",
                "{{scenario}}",
                "</scenario>",
                "",
                "<post_history_instructions>",
                "{{post_history_instructions}}",
                "</post_history_instructions>",
            ].join("\n"),
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "after-scenario",
        },
        {
            id: dynamicPromptIds.chatExamples,
            title: "Chat Examples",
            role: "system",
            content: "",
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "after-character",
        },
        {
            id: dynamicPromptIds.chatHistory,
            title: "Chat History",
            role: "system",
            content: ["<chat_history>", "{{chat_history}}", "</chat_history>"].join("\n"),
            systemPrompt: false,
            marker: true,
            injectionPosition: "none",
            injectionDepth: 4,
            forbidOverrides: false,
            anchor: "before-history",
        },
    ];

    return {
        id: "default",
        title: "Default",
        prompts,
        promptOrder: prompts.map((prompt) => ({
            promptId: prompt.id,
            enabled: true,
        })),
        generation: defaultPresetGenerationSettings,
        createdAt: now,
        updatedAt: now,
    };
}

export const defaultPresetCollection: PresetCollection = {
    activePresetId: "default",
    presets: [createDefaultPreset("2026-01-01T00:00:00.000Z")],
};
